Create yocto recipe for deploying binaries
Mini-air-quality-station/meta-air-quality pull request #3
Opened 2023-01-17 21:45 UTC by esesyn01

2023-01-17 21:45 UTC, esesyn01 commented
@punfil

2023-01-19 21:52 UTC, punfil requested changes

2023-01-19 21:52 UTC, punfil commented on kas/kas-common.yml
> +    refspec: 6f5771d2bcfbfb8f8ce17b455c29a5703f2027c9
Please manage commits.

2023-01-19 22:01 UTC, esesyn01 commented on kas/kas-common.yml
> +    refspec: 6f5771d2bcfbfb8f8ce17b455c29a5703f2027c9
@punfil done

2023-01-19 22:08 UTC, punfil approved these changes

2023-01-19 22:09 UTC, merged